@php
    $suggestions = config('ai.suggested_questions');
@endphp

<section id="ask" data-reveal tabindex="0" aria-labelledby="ask-heading" class="border-t border-line px-[7vw] py-24">
    <x-portfolio.section-intro
        eyebrow="Ask"
        title="Ask my AI assistant"
        heading-id="ask-heading"
        lead="Curious about my experience, projects, leadership style, or technical background? Ask a question."
    />

    <div class="mx-auto max-w-[860px]">
        {{-- resources/js/ask/main.tsx replaces the contents of this element
             with the interactive assistant. What is inside is the no-JS
             version: the same questions, answered by the rest of the page. --}}
        <div
            data-ask-root
            data-endpoint="{{ route('ask') }}"
            data-suggestions='@json($suggestions)'
            data-max-length="{{ config('ai.conversation.max_question_length') }}"
            data-max-history="{{ config('ai.conversation.max_history') }}"
            data-contact-href="#contact"
        >
            <div class="rounded-[24px] border border-line bg-surface-deep px-6 py-8 min-[601px]:px-9">
                <p class="mb-5 text-[15.5px] leading-[1.65] text-body">
                    The assistant answers questions like these from what I've documented here. It needs JavaScript to run —
                    with it off, the answers are in the sections above, or you can
                    <a href="#contact" class="font-semibold text-accent underline-offset-4 hover:underline">ask me directly</a>.
                </p>
                <ul class="flex flex-wrap gap-2.5">
                    @foreach ($suggestions as $question)
                        <li class="rounded-full border border-line-strong bg-surface px-4 py-2 text-[13.5px] font-medium text-muted">{{ $question }}</li>
                    @endforeach
                </ul>
            </div>
        </div>

        <p class="mt-4 text-center text-[12.5px] leading-[1.6] text-faint">
            Answers are generated by an AI model from Miguel's own notes and may be imperfect. It won't invent experience:
            if something isn't documented, it says so.
        </p>
    </div>
</section>
